/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package steelconnections;

/**
 *
 * @author malgo
 */
public class BeamToBeam extends javax.swing.JFrame {

    /**
     * Creates new form BeamToBeam
     */
    public BeamToBeam() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtD0 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtA = new javax.swing.JTextField();
        txtAs = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFyb = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFub = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtGammaM2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnCalculate = new javax.swing.JButton();
        txtAlfaV = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtFvRd = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtE1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtE2 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtP1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtT = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        cboKlasaSrub = new javax.swing.JComboBox<>();
        cboSrednicaSrub = new javax.swing.JComboBox<>();
        cboKlasaStali = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        cboPlaszczyznaScinania = new javax.swing.JComboBox<>();
        jLabel31 = new javax.swing.JLabel();
        txtFy = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtAv = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txtFu = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        txtFtRd = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        cboLebWpuszczany = new javax.swing.JComboBox<>();
        btnRaport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("d=");

        jLabel2.setText("d0=");

        txtD0.setText("13.0");

        jLabel3.setText("A=");

        txtA.setText("113.0");

        txtAs.setText("84.3");

        jLabel4.setText("As=");

        txtFyb.setText("240.0");

        jLabel5.setText("fyb=");

        txtFub.setText("400.0");

        jLabel6.setText("fub=");

        txtGammaM2.setText("1.25");

        jLabel7.setText("Ym2=");

        btnCalculate.setText("Oblicz");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        txtAlfaV.setText("0.6");

        jLabel8.setText("alfaV=");

        jLabel9.setText("[mm]");

        jLabel10.setText("[mm]");

        jLabel11.setText("[mm2]");

        jLabel12.setText("[mm2]");

        jLabel13.setText("[N/mm2]");

        jLabel14.setText("[N/mm2]");

        jLabel15.setText("[-]");

        jLabel16.setText("[-]");

        jLabel17.setText("Fv,Rd=");

        jLabel18.setText("[kN]");

        jLabel19.setText("e1=");

        txtE1.setText("25");

        jLabel20.setText("[mm]");

        jLabel21.setText("e2=");

        txtE2.setText("25");

        jLabel22.setText("[mm]");

        jLabel23.setText("p1=");

        txtP1.setText("50");

        jLabel24.setText("[mm]");

        jLabel25.setText("[-]");

        txtT.setText("5.0");

        jLabel26.setText("t=");

        jLabel27.setForeground(new java.awt.Color(153, 153, 153));
        jLabel27.setText("Copyright (c) 2018 by Jarosław Kowalczyk");

        cboKlasaSrub.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4.6", "4.8", "5.6", "5.8", "6.8", "8.8", "10.9" }));
        cboKlasaSrub.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboKlasaSrubItemStateChanged(evt);
            }
        });

        cboSrednicaSrub.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12", "16", "20", "22", "24", "27", "30", "36" }));
        cboSrednicaSrub.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboSrednicaSrubItemStateChanged(evt);
            }
        });

        cboKlasaStali.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S235", "S275", "S355", "S450" }));
        cboKlasaStali.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboKlasaStaliItemStateChanged(evt);
            }
        });

        jLabel28.setText("Klasa śrub:");

        jLabel29.setText("Klasa stali:");

        jLabel30.setText("Pł. ścinania:");

        cboPlaszczyznaScinania.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "gwintowana", "niegwintowana" }));
        cboPlaszczyznaScinania.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboPlaszczyznaScinaniaItemStateChanged(evt);
            }
        });

        jLabel31.setText("fy=");

        txtFy.setText("235.0");

        jLabel32.setText("[N/mm2]");

        jLabel33.setText("Av=");

        txtAv.setText("84.3");

        jLabel34.setText("[mm2]");

        jLabel35.setText("fu=");

        txtFu.setText("360.0");

        jLabel36.setText("[N/mm2]");

        jLabel37.setText("Ft,Rd=");

        jLabel38.setText("[kN]");

        jLabel39.setText("Łeb śruby wpuszczany:");

        cboLebWpuszczany.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NIE", "TAK" }));
        cboLebWpuszczany.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboLebWpuszczanyItemStateChanged(evt);
            }
        });

        btnRaport.setText("Raport");
        btnRaport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel26)
                        .addGap(18, 18, 18)
                        .addComponent(txtT, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel25))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(txtFvRd, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtGammaM2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(18, 18, 18)
                                .addComponent(txtE2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel22))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addComponent(txtE1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel20))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(23, 23, 23)
                                .addComponent(txtP1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel24)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel37)
                            .addGap(18, 18, 18)
                            .addComponent(txtFtRd, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel38))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboLebWpuszczany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(124, 124, 124)
                        .addComponent(btnRaport)
                        .addGap(18, 18, 18)
                        .addComponent(btnCalculate))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel35)
                            .addGap(18, 18, 18)
                            .addComponent(txtFu, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel36))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel29)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cboKlasaStali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(92, 92, 92))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(cboSrednicaSrub, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel9)
                                    .addGap(96, 96, 96)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtAs, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtD0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel12)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel31)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtFy, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel32)))
                            .addGap(8, 8, 8))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel28)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cboKlasaSrub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(95, 95, 95)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtFub, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtFyb, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13)
                                .addComponent(jLabel14))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(240, 240, 240)
                            .addComponent(jLabel33)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtAv, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel34))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(223, 223, 223)
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtAlfaV, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel16)
                            .addGap(36, 36, 36)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboPlaszczyznaScinania, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtD0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9)
                    .addComponent(cboSrednicaSrub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGammaM2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboKlasaStali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(txtFy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32)
                    .addComponent(txtT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35)
                    .addComponent(jLabel36))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFvRd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cboKlasaSrub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel28))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtFyb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtFub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel14))))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(cboPlaszczyznaScinania, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33)
                            .addComponent(jLabel34))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAlfaV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel16))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel39)
                        .addComponent(cboLebWpuszczany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFtRd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel37)
                        .addComponent(jLabel38)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnCalculate)
                                .addComponent(btnRaport))
                            .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtE1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtE2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24))
                        .addGap(23, 23, 23))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

        String klasaSrub;
        String srednicaSrub;
        String klasaStali;
        String reportString;
        
        double fyb;
        double fub;
        
        double av;
        double a;
        double as;
        double fVRd;
        double fVsRd;
        double fTRd;
        
        double d;
        double d0;

        double gammaM2;
        double alfaV;
        
        double k1;
        double k1a;
        double k1b;
        double e1;
        double e2;
        double p1;
        double alfaB1;
        double alfaB2;
        double alfaD1;
        double alfaD2;
        double fBRd1;
        double t;
        double fBRd2;
        
        double fy;
        double fu;
        
        double k2;
        
    public double roundUpToNplace(double number, int numberAfterComa){
           String s = String.valueOf(number);
           double zaokr;
           zaokr = Double.parseDouble(s);
           zaokr *= numberAfterComa;
           zaokr = Math.round(zaokr);
           zaokr /= numberAfterComa;
           
           return zaokr;
}
    
    public void steelStrength(){
        klasaStali = cboKlasaStali.getSelectedItem().toString();
        
        switch (klasaStali)
        {
            case "S235":
                fy = 235;
                fu = 360;
                break;
            case "S275":
                fy = 275;
                fu = 430;
                break;
            case "S355":
                fy = 355;
                fu = 510;
                break;
            case "S450":
                fy = 440;
                fu = 550;
                break;
            default:
            System.out.println("NIEPOPRAWNE DANE");
            break;
        }
        
        txtFy.setText(Double.toString(fy));
        txtFu.setText(Double.toString(fu));
    }
    
    public void boltGrades() {
        klasaSrub = cboKlasaSrub.getSelectedItem().toString();
        
        switch (klasaSrub)
        {
            case "4.6":
                fyb = 240;
                fub = 400;
                break;
            case "4.8":
                fyb = 320;
                fub = 400;
                break;
            case "5.6":
                fyb = 300;
                fub = 500;
                break;
            case "5.8":
                fyb = 400;
                fub = 500;
                break;
            case "6.8":
                fyb = 480;
                fub = 600;
                break;
            case "8.8":
                fyb = 640;
                fub = 800;
                break;
            case "10.9":
                fyb = 900;
                fub = 1000;
                break;
            default:
                System.out.println("NIEPRAWIDŁOWE DANE");
                break;
        }
        
        txtFyb.setText(Double.toString(fyb));
        txtFub.setText(Double.toString(fub));
    }
        
    public void boltAndHolesCharacteristics(){
        srednicaSrub = cboSrednicaSrub.getSelectedItem().toString();
        switch (srednicaSrub)
        {
            case "12":
                d = 12;
                d0 = d + 1;
                a = 113;
                as = 84.3;
                break;
            case "16":
                d = 16;
                d0 = d + 2;
                a = 201;
                as = 157;
                break;
            case "20":
                d = 20;
                d0 = d + 2;
                a = 314;
                as = 245;
                break;
            case "22":
                d = 22;
                d0 = d + 2;
                a = 380;
                as = 303;
                break;
            case "24":
                d = 24;
                d0 = d + 2;
                a = 452;
                as = 353;
                break;
            case "27":
                d = 27;
                d0 = d + 3;
                a = 573;
                as = 459;
                break;
            case "30":
                d = 30;
                d0 = d + 3;
                a = 707;
                as = 561;
                break;
            case "36":
                d = 36;
                d0 = d + 3;
                a = 1018;
                as = 817;
                break;
            default:
                System.out.println("NIEPRAWIDŁOWE DANE");
                break;
        }
        
        alfaVthreadedUnthreaderdBolt();
        
        txtD0.setText(Double.toString(d0));
        txtA.setText(Double.toString(a));
        txtAs.setText(Double.toString(as));
        
    }
    
    private void clearTextField(){
        txtFvRd.setText("");
        txtFtRd.setText("");
    }
    
    private void alfaVthreadedUnthreaderdBolt() {
        if (cboPlaszczyznaScinania.getSelectedItem().equals("gwintowana") && cboKlasaSrub.getSelectedItem().equals("4.6")){
            av = as;
            alfaV = 0.6;
        } else if (cboPlaszczyznaScinania.getSelectedItem().equals("gwintowana") && cboKlasaSrub.getSelectedItem().equals("4.8")) {
            av = as;
            alfaV = 0.5;
        } else if (cboPlaszczyznaScinania.getSelectedItem().equals("gwintowana") && cboKlasaSrub.getSelectedItem().equals("5.6")) {
            av = as;
            alfaV = 0.6;
        } else if (cboPlaszczyznaScinania.getSelectedItem().equals("gwintowana") && cboKlasaSrub.getSelectedItem().equals("5.8")) {
            av = as;
            alfaV = 0.5;
        } else if (cboPlaszczyznaScinania.getSelectedItem().equals("gwintowana") && cboKlasaSrub.getSelectedItem().equals("6.8")) {
            av = as;
            alfaV = 0.5;
        } else if (cboPlaszczyznaScinania.getSelectedItem().equals("gwintowana") && cboKlasaSrub.getSelectedItem().equals("8.8")) {
            av = as;
            alfaV = 0.6;
        } else if (cboPlaszczyznaScinania.getSelectedItem().equals("gwintowana") && cboKlasaSrub.getSelectedItem().equals("10.9")) {
            av = as;
            alfaV = 0.5;
        } else if (cboPlaszczyznaScinania.getSelectedItem().equals("niegwintowana")) {
            av = a;
            alfaV = 0.6;
        }
        
        txtAv.setText(Double.toString(av));
        txtAlfaV.setText(Double.toString(alfaV));
    }
    
    private void k2Checker() {
        if (cboLebWpuszczany.getSelectedItem().equals("TAK")) {
            k2 = 0.63;
        } else {
            k2 = 0.9;
        }
    }
     
    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        
        steelStrength();
        boltGrades();
        boltAndHolesCharacteristics();
        alfaVthreadedUnthreaderdBolt();
        k2Checker();
        
        
        // kierunek obciazenia i zaleznosc alfad
    
        
        d0 = Double.parseDouble(txtD0.getText());
        gammaM2 = Double.parseDouble(txtGammaM2.getText());
        alfaV = Double.parseDouble(txtAlfaV.getText());
        t = Double.parseDouble(txtT.getText());
        
        e1 = Double.parseDouble(txtE1.getText());
        e2 = Double.parseDouble(txtE2.getText());
        p1 = Double.parseDouble(txtP1.getText());
        
        // Nośność śruby na ścinanie
        fVRd = ((alfaV * fub * av) / gammaM2) * 0.001;
        fVRd = roundUpToNplace(fVRd, 100);
        txtFvRd.setText(Double.toString(fVRd));
        
        // Nosnosc srub na rozciąganie
        fTRd = ((k2 * fub * as) / gammaM2) * 0.001;
        fTRd = roundUpToNplace(fTRd, 100);
        txtFtRd.setText(Double.toString(fTRd));
        
        // Nośność śruby na docisk do środnika belki (t - cieńszy z elementów)
        
        // Śruba skrajna
        k1a = 2.8 * (e2/d0) - 1.7;
        k1b = 2.5;
        System.out.println(k1a);
        
        k1 = Math.min(k1a, k1b);
        System.out.println("k1 = " + k1);
        
        alfaD1 = e1 / (3 * d0);
        
        // Wybrać z listy w zależności od klasy stali
        //fu = 360;
        
        alfaB1 = Math.min(Math.min(alfaD1, fub / fu), 1.0);
        System.out.println("alfaD1 = " + alfaD1);
        System.out.println(fub/fu);
        System.out.println("alfaB1 = " + alfaB1);
        
        fBRd1 = ((k1 * alfaB1 * fu * d * t) / gammaM2) * 0.001;
        
        System.out.println("fbrd1 = " + fBRd1);
        
        // Śruba pośrednia
        alfaD2 = (p1 / (3 * d0)) - 0.25;
        alfaB2 = Math.min(Math.min(alfaD2, fub / fu), 1.0);
        System.out.println("alfaD2 = " + alfaD2);
        System.out.println(fub/fu);
        System.out.println("alfaB2 = " + alfaB2);
        
        fBRd2 = ((k1 * alfaB2 * fu * d * t) / gammaM2) * 0.001;
        
        System.out.println("fbrd2 = " + fBRd2);
        
    }//GEN-LAST:event_btnCalculateActionPerformed

    private String makeStringReport() {
        reportString = "Połączenie belka-belka \n\n"
                + "Klasa stali: \t" + cboKlasaStali.getSelectedItem().toString() + "\n"
                + "Granica plastyczności stali: \t\t fy= " + fy + "\t [MPa]" + "\n"
                + "Wytrzymałość stali na rozciąganie: \t fu= " + fu + "\t [MPa]" + "\n"
                + "\n"
                + "Średnica śruby: \t d= " + d + "\t [mm]" + "\n"
                + "Średnica otworu: \t d0= " + d0 + "\t [mm]" + "\n"
                + "Pole przekroju trzpienia: \t A= " + a + "\t [mm2]" + "\n"
                + "Pole przekroju rdzenia: \t As= " + as + "\t [mm2]" + "\n"
                + "\n"
                + "Klasa śrub: \t" + cboKlasaSrub.getSelectedItem().toString() + "\n"
                + "Granica plastyczności stali śruby: \t fyb= " + fyb + "\t [MPa]" + "\n"
                + "Wytrzymałość stali śruby na rozciąganie: \t fub= " + fub + "\t [MPa]" + "\n"
                ;
        return reportString;
    }
    
    private void cboSrednicaSrubItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboSrednicaSrubItemStateChanged
        clearTextField();
        boltGrades();
        boltAndHolesCharacteristics();
    }//GEN-LAST:event_cboSrednicaSrubItemStateChanged

    private void cboKlasaSrubItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboKlasaSrubItemStateChanged
        clearTextField();
        boltGrades();
        boltAndHolesCharacteristics();
        alfaVthreadedUnthreaderdBolt();
    }//GEN-LAST:event_cboKlasaSrubItemStateChanged

    private void cboKlasaStaliItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboKlasaStaliItemStateChanged
        clearTextField();
        boltGrades();
        steelStrength();
    }//GEN-LAST:event_cboKlasaStaliItemStateChanged

    private void cboPlaszczyznaScinaniaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboPlaszczyznaScinaniaItemStateChanged
        clearTextField();
        alfaVthreadedUnthreaderdBolt();
    }//GEN-LAST:event_cboPlaszczyznaScinaniaItemStateChanged

    private void cboLebWpuszczanyItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboLebWpuszczanyItemStateChanged
        clearTextField();
        k2Checker();
    }//GEN-LAST:event_cboLebWpuszczanyItemStateChanged

    private void btnRaportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaportActionPerformed
        Raport raport = new Raport(makeStringReport());
        raport.setVisible(true);
        raport.pack();
        raport.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnRaportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BeamToBeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BeamToBeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BeamToBeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BeamToBeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BeamToBeam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnRaport;
    private javax.swing.JComboBox<String> cboKlasaSrub;
    private javax.swing.JComboBox<String> cboKlasaStali;
    private javax.swing.JComboBox<String> cboLebWpuszczany;
    private javax.swing.JComboBox<String> cboPlaszczyznaScinania;
    private javax.swing.JComboBox<String> cboSrednicaSrub;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtAlfaV;
    private javax.swing.JTextField txtAs;
    private javax.swing.JTextField txtAv;
    private javax.swing.JTextField txtD0;
    private javax.swing.JTextField txtE1;
    private javax.swing.JTextField txtE2;
    private javax.swing.JTextField txtFtRd;
    private javax.swing.JTextField txtFu;
    private javax.swing.JTextField txtFub;
    private javax.swing.JTextField txtFvRd;
    private javax.swing.JTextField txtFy;
    private javax.swing.JTextField txtFyb;
    private javax.swing.JTextField txtGammaM2;
    private javax.swing.JTextField txtP1;
    private javax.swing.JTextField txtT;
    // End of variables declaration//GEN-END:variables
}
