/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package steelconnections;

import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author malgo
 */
public class BeamToBeam extends javax.swing.JFrame {

    /**
     * Creates new form BeamToBeam
     */
    public BeamToBeam() {
        initComponents();
        setIcon();
        setTitle("SteelConnections - Beam to beam");
        
        rowChecker();
    }
    
    public void setIcon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("ico.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cboSrednicaSrub = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        cboKlasaStali = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        cboKlasaSrub = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtD0 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtA = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtAs = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtFy = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txtFu = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFyb = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFub = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        cboPlaszczyznaScinania = new javax.swing.JComboBox<>();
        jLabel33 = new javax.swing.JLabel();
        txtAv = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtAlfaV = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        cboLebWpuszczany = new javax.swing.JComboBox<>();
        btnRaport = new javax.swing.JButton();
        btnCalculate = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        cboBoltColumn = new javax.swing.JComboBox<>();
        jLabel41 = new javax.swing.JLabel();
        cboBoltRow = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        txtFvRd = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        txtFtRd = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtGammaM2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtT = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jPanel_img = new javax.swing.JPanel();
        lbl1_2 = new javax.swing.JLabel();
        lbl1_3 = new javax.swing.JLabel();
        lbl1_4 = new javax.swing.JLabel();
        lbl1_5 = new javax.swing.JLabel();
        lbl1_6 = new javax.swing.JLabel();
        lbl2_2 = new javax.swing.JLabel();
        lbl2_3 = new javax.swing.JLabel();
        lbl2_4 = new javax.swing.JLabel();
        lbl2_5 = new javax.swing.JLabel();
        lbl2_6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtE1 = new javax.swing.JTextField();
        txtE2 = new javax.swing.JTextField();
        txtP1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtE1Min = new javax.swing.JTextField();
        txtP1Min = new javax.swing.JTextField();
        txtE2Min = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        txtP2 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        txtP2Min = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setName(""); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Parametry połączenia"));
        jPanel2.setName(""); // NOI18N

        jLabel1.setText("d=");

        cboSrednicaSrub.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12", "16", "20", "22", "24", "27", "30", "36" }));
        cboSrednicaSrub.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboSrednicaSrubItemStateChanged(evt);
            }
        });

        jLabel9.setText("[mm]");

        jLabel29.setText("Klasa stali:");

        cboKlasaStali.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S235", "S275", "S355", "S450" }));
        cboKlasaStali.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboKlasaStaliItemStateChanged(evt);
            }
        });

        jLabel28.setText("Klasa śrub:");

        cboKlasaSrub.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4.6", "4.8", "5.6", "5.8", "6.8", "8.8", "10.9" }));
        cboKlasaSrub.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboKlasaSrubItemStateChanged(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel2.setText("d0=");
        jLabel2.setPreferredSize(new java.awt.Dimension(28, 16));

        txtD0.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtD0.setText("13.0");

        jLabel10.setText("[mm]");

        jLabel3.setText("A=");
        jLabel3.setPreferredSize(new java.awt.Dimension(28, 16));

        txtA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtA.setText("113.0");

        jLabel11.setText("[mm2]");

        jLabel4.setText("As=");
        jLabel4.setPreferredSize(new java.awt.Dimension(28, 16));

        txtAs.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAs.setText("84.3");

        jLabel12.setText("[mm2]");

        txtFy.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFy.setText("235.0");

        jLabel32.setText("[N/mm2]");

        jLabel31.setText("fy=");
        jLabel31.setPreferredSize(new java.awt.Dimension(28, 16));

        jLabel35.setText("fu=");
        jLabel35.setPreferredSize(new java.awt.Dimension(28, 16));

        txtFu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFu.setText("360.0");

        jLabel36.setText("[N/mm2]");

        jLabel13.setText("[N/mm2]");

        jLabel5.setText("fyb=");
        jLabel5.setPreferredSize(new java.awt.Dimension(28, 16));

        txtFyb.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFyb.setText("240.0");

        jLabel6.setText("fub=");
        jLabel6.setPreferredSize(new java.awt.Dimension(28, 16));

        txtFub.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFub.setText("400.0");

        jLabel14.setText("[N/mm2]");

        jLabel30.setText("Płaszczyzna ścinania:");

        cboPlaszczyznaScinania.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "gwintowana", "niegwintowana" }));
        cboPlaszczyznaScinania.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboPlaszczyznaScinaniaItemStateChanged(evt);
            }
        });

        jLabel33.setText("Av=");
        jLabel33.setPreferredSize(new java.awt.Dimension(28, 16));

        txtAv.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAv.setText("84.3");

        jLabel34.setText("[mm2]");

        jLabel8.setText("alfaV=");

        txtAlfaV.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAlfaV.setText("0.6");

        jLabel16.setText("[-]");

        jLabel39.setText("Łeb śruby wpuszczany:");

        cboLebWpuszczany.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NIE", "TAK" }));
        cboLebWpuszczany.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboLebWpuszczanyItemStateChanged(evt);
            }
        });

        btnRaport.setText("Raport");
        btnRaport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaportActionPerformed(evt);
            }
        });

        btnCalculate.setText("Oblicz");
        btnCalculate.setMaximumSize(new java.awt.Dimension(68, 32));
        btnCalculate.setMinimumSize(new java.awt.Dimension(68, 32));
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cboSrednicaSrub, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboKlasaStali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboKlasaSrub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel30)
                    .addComponent(cboPlaszczyznaScinania, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39)
                    .addComponent(cboLebWpuszczany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtD0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFy, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel32))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFyb, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAv, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel34)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel36))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFub, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)))
                        .addGap(163, 163, 163))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAlfaV, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnRaport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAs, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel9)
                            .addComponent(cboSrednicaSrub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboKlasaStali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboKlasaSrub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtD0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(txtAs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32)
                            .addComponent(txtFu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFyb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(txtFub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboPlaszczyznaScinania, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtAv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel34)
                                    .addComponent(txtAlfaV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel16))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboLebWpuszczany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRaport)
                        .addContainerGap())))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Rozmieszczenie śrub"));

        jLabel40.setText("Rzędy śrub:");

        cboBoltColumn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "wybierz", "1", "2" }));
        cboBoltColumn.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboBoltColumnItemStateChanged(evt);
            }
        });

        jLabel41.setText("Wiersze śrub:");

        cboBoltRow.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "wybierz", "2", "3", "4", "5", "6" }));
        cboBoltRow.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboBoltRowItemStateChanged(evt);
            }
        });

        jLabel17.setText("Fv,Rd=");

        jLabel18.setText("[kN]");

        jLabel37.setText("Ft,Rd=");

        jLabel38.setText("[kN]");

        jLabel7.setText("Ym2=");

        txtGammaM2.setText("1.25");

        jLabel15.setText("[-]");

        jLabel26.setText("t=");

        txtT.setText("5.0");

        jLabel25.setText("[-]");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtGammaM2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel26)
                        .addGap(18, 18, 18)
                        .addComponent(txtT, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel25)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel40)
                                .addGap(18, 18, 18)
                                .addComponent(cboBoltColumn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel41)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboBoltRow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel37)
                                .addGap(18, 18, 18)
                                .addComponent(txtFtRd, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel38))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(txtFvRd, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel18)))))
                .addGap(53, 53, 53))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFvRd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17)
                        .addComponent(jLabel18))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel40)
                        .addComponent(cboBoltColumn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFtRd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel37)
                        .addComponent(jLabel38))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel41)
                        .addComponent(cboBoltRow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel26)
                        .addComponent(jLabel25))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtGammaM2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel15)))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        jPanel_img.setMaximumSize(new java.awt.Dimension(300, 300));
        jPanel_img.setMinimumSize(new java.awt.Dimension(300, 300));
        jPanel_img.setPreferredSize(new java.awt.Dimension(300, 300));

        lbl1_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1_2.png"))); // NOI18N

        lbl1_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1_3.png"))); // NOI18N

        lbl1_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1_4.png"))); // NOI18N

        lbl1_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1_5.png"))); // NOI18N

        lbl1_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1_6.png"))); // NOI18N

        lbl2_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2_2.png"))); // NOI18N

        lbl2_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2_3.png"))); // NOI18N

        lbl2_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2_4.png"))); // NOI18N

        lbl2_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2_5.png"))); // NOI18N

        lbl2_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2_6.png"))); // NOI18N

        javax.swing.GroupLayout jPanel_imgLayout = new javax.swing.GroupLayout(jPanel_img);
        jPanel_img.setLayout(jPanel_imgLayout);
        jPanel_imgLayout.setHorizontalGroup(
            jPanel_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(jPanel_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_imgLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lbl1_2)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_imgLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lbl1_3)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_imgLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lbl1_4)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_imgLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lbl1_5)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_imgLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lbl1_6)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_imgLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lbl2_2)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_imgLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lbl2_3)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_imgLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lbl2_4)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_imgLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lbl2_5)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_imgLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lbl2_6)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel_imgLayout.setVerticalGroup(
            jPanel_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(jPanel_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_imgLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lbl1_2)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_imgLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lbl1_3)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_imgLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lbl1_4)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_imgLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lbl1_5)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_imgLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lbl1_6)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_imgLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lbl2_2)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_imgLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lbl2_3)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_imgLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lbl2_4)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_imgLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lbl2_5)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_imgLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lbl2_6)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Rozmieszczenie otworów"));

        jLabel19.setText("e1=");

        jLabel21.setText("e2=");

        jLabel23.setText("p1=");

        txtE1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtE1.setText("25");

        txtE2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtE2.setText("25");

        txtP1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtP1.setText("50");

        jLabel20.setText("[mm]     >=     1,2 x d0 =");

        jLabel22.setText("[mm]     >=     1,2 x d0 =");

        jLabel24.setText("[mm]     >=     2,2 x d0 =");

        txtE1Min.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtP1Min.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtE2Min.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel42.setText("p2=");

        txtP2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtP2.setText("50");

        jLabel43.setText("[mm]     >=     2,4 x d0 =");

        txtP2Min.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtE1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtE1Min, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtP1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtP1Min, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtE2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtE2Min, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel42)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtP2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel43)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtP2Min, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtE1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(txtE1Min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(txtP1Min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtE2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(txtE2Min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42)
                    .addComponent(jLabel43)
                    .addComponent(txtP2Min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_img, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel_img, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.getAccessibleContext().setAccessibleName("");

        jLabel27.setForeground(new java.awt.Color(153, 153, 153));
        jLabel27.setText("Copyright (c) 2019 by Jarosław Kowalczyk");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27)
                .addGap(380, 380, 380))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addContainerGap())
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cboBoltRowItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboBoltRowItemStateChanged
        rowChecker();
    }//GEN-LAST:event_cboBoltRowItemStateChanged

    private void cboBoltColumnItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboBoltColumnItemStateChanged
       imgClear();
       cboBoltRow.setSelectedItem("wybierz");
    }//GEN-LAST:event_cboBoltColumnItemStateChanged

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed

        steelStrength();
        boltGrades();
        boltAndHolesCharacteristics();
        alfaVthreadedUnthreaderdBolt();
        k2Checker();

        // kierunek obciazenia i zaleznosc alfad

        d0 = Double.parseDouble(txtD0.getText());
        gammaM2 = Double.parseDouble(txtGammaM2.getText());
        alfaV = Double.parseDouble(txtAlfaV.getText());
        t = Double.parseDouble(txtT.getText());

        e1 = Double.parseDouble(txtE1.getText());
        e2 = Double.parseDouble(txtE2.getText());
        p1 = Double.parseDouble(txtP1.getText());
        p2 = Double.parseDouble(txtP2.getText());

        // Nośność śruby na ścinanie
        fVRd = ((alfaV * fub * av) / gammaM2) * 0.001;
        fVRd = roundUpToNplace(fVRd, 100);
        txtFvRd.setText(Double.toString(fVRd));

        // Nosnosc srub na rozciąganie
        fTRd = ((k2 * fub * as) / gammaM2) * 0.001;
        fTRd = roundUpToNplace(fTRd, 100);
        txtFtRd.setText(Double.toString(fTRd));

        // Nośność śruby na docisk do środnika belki (t - cieńszy z elementów)

        // Śruba skrajna
        k1a = 2.8 * (e2/d0) - 1.7;
        k1b = 2.5;
        System.out.println(k1a);

        k1 = Math.min(k1a, k1b);
        System.out.println("k1 = " + k1);

        alfaD1 = e1 / (3 * d0);

        // Wybrać z listy w zależności od klasy stali
        //fu = 360;

        alfaB1 = Math.min(Math.min(alfaD1, fub / fu), 1.0);
        System.out.println("alfaD1 = " + alfaD1);
        System.out.println(fub/fu);
        System.out.println("alfaB1 = " + alfaB1);

        fBRd1 = ((k1 * alfaB1 * fu * d * t) / gammaM2) * 0.001;

        System.out.println("fbrd1 = " + fBRd1);

        // Śruba pośrednia
        alfaD2 = (p1 / (3 * d0)) - 0.25;
        alfaB2 = Math.min(Math.min(alfaD2, fub / fu), 1.0);
        System.out.println("alfaD2 = " + alfaD2);
        System.out.println(fub/fu);
        System.out.println("alfaB2 = " + alfaB2);

        fBRd2 = ((k1 * alfaB2 * fu * d * t) / gammaM2) * 0.001;

        System.out.println("fbrd2 = " + fBRd2);
        
        // Holes checkers
        e1Checker();
        p1Checker();
        e2Checker();
        p2Checker();
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnRaportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaportActionPerformed
        Raport raport = new Raport(makeStringReport());
        raport.setVisible(true);
        raport.pack();
        raport.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnRaportActionPerformed

    private void cboLebWpuszczanyItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboLebWpuszczanyItemStateChanged
        clearTextField();
        k2Checker();
    }//GEN-LAST:event_cboLebWpuszczanyItemStateChanged

    private void cboPlaszczyznaScinaniaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboPlaszczyznaScinaniaItemStateChanged
        clearTextField();
        alfaVthreadedUnthreaderdBolt();
    }//GEN-LAST:event_cboPlaszczyznaScinaniaItemStateChanged

    private void cboKlasaSrubItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboKlasaSrubItemStateChanged
        clearTextField();
        boltGrades();
        boltAndHolesCharacteristics();
        alfaVthreadedUnthreaderdBolt();
    }//GEN-LAST:event_cboKlasaSrubItemStateChanged

    private void cboKlasaStaliItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboKlasaStaliItemStateChanged
        clearTextField();
        boltGrades();
        steelStrength();
    }//GEN-LAST:event_cboKlasaStaliItemStateChanged

    private void cboSrednicaSrubItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboSrednicaSrubItemStateChanged
        clearTextField();
        boltGrades();
        boltAndHolesCharacteristics();
    }//GEN-LAST:event_cboSrednicaSrubItemStateChanged
    
        UnicodeSymbols unicodeSymbols = new UnicodeSymbols();
        
        String klasaSrub;
        String srednicaSrub;
        String klasaStali;
        String reportString;
        String boltColumn;
        String boltRow;
        
        double fyb;
        double fub;
        
        double av;
        double a;
        double as;
        double fVRd;
        double fVsRd;
        double fTRd;
        
        double d;
        double d0;

        double gammaM2;
        double alfaV;
        
        double k1;
        double k1a;
        double k1b;
        double e1;
        double e2;
        double p1;
        double p2;
        double alfaB1;
        double alfaB2;
        double alfaD1;
        double alfaD2;
        double fBRd1;
        double t;
        double fBRd2;
        
        double fy;
        double fu;
        
        double k2;
        
    public double roundUpToNplace(double number, int numberAfterComa){
           String s = String.valueOf(number);
           double zaokr;
           zaokr = Double.parseDouble(s);
           zaokr *= numberAfterComa;
           zaokr = Math.round(zaokr);
           zaokr /= numberAfterComa;
           
           return zaokr;
}
    
    public void steelStrength(){
        klasaStali = cboKlasaStali.getSelectedItem().toString();
        
        switch (klasaStali)
        {
            case "S235":
                fy = 235;
                fu = 360;
                break;
            case "S275":
                fy = 275;
                fu = 430;
                break;
            case "S355":
                fy = 355;
                fu = 510;
                break;
            case "S450":
                fy = 440;
                fu = 550;
                break;
            default:
            System.out.println("NIEPOPRAWNE DANE");
            break;
        }
        
        txtFy.setText(Double.toString(fy));
        txtFu.setText(Double.toString(fu));
    }
    
    public void boltGrades() {
        klasaSrub = cboKlasaSrub.getSelectedItem().toString();
        
        switch (klasaSrub)
        {
            case "4.6":
                fyb = 240;
                fub = 400;
                break;
            case "4.8":
                fyb = 320;
                fub = 400;
                break;
            case "5.6":
                fyb = 300;
                fub = 500;
                break;
            case "5.8":
                fyb = 400;
                fub = 500;
                break;
            case "6.8":
                fyb = 480;
                fub = 600;
                break;
            case "8.8":
                fyb = 640;
                fub = 800;
                break;
            case "10.9":
                fyb = 900;
                fub = 1000;
                break;
            default:
                System.out.println("NIEPRAWIDŁOWE DANE");
                break;
        }
        
        txtFyb.setText(Double.toString(fyb));
        txtFub.setText(Double.toString(fub));
    }
        
    public void boltAndHolesCharacteristics(){
        srednicaSrub = cboSrednicaSrub.getSelectedItem().toString();
        switch (srednicaSrub)
        {
            case "12":
                d = 12;
                d0 = d + 1;
                a = 113;
                as = 84.3;
                break;
            case "16":
                d = 16;
                d0 = d + 2;
                a = 201;
                as = 157;
                break;
            case "20":
                d = 20;
                d0 = d + 2;
                a = 314;
                as = 245;
                break;
            case "22":
                d = 22;
                d0 = d + 2;
                a = 380;
                as = 303;
                break;
            case "24":
                d = 24;
                d0 = d + 2;
                a = 452;
                as = 353;
                break;
            case "27":
                d = 27;
                d0 = d + 3;
                a = 573;
                as = 459;
                break;
            case "30":
                d = 30;
                d0 = d + 3;
                a = 707;
                as = 561;
                break;
            case "36":
                d = 36;
                d0 = d + 3;
                a = 1018;
                as = 817;
                break;
            default:
                System.out.println("NIEPRAWIDŁOWE DANE");
                break;
        }
        
        alfaVthreadedUnthreaderdBolt();
        
        txtD0.setText(Double.toString(d0));
        txtA.setText(Double.toString(a));
        txtAs.setText(Double.toString(as));
        
    }
    
    private void clearTextField(){
        txtFvRd.setText("");
        txtFtRd.setText("");
    }
    
    private void alfaVthreadedUnthreaderdBolt() {
        if (cboPlaszczyznaScinania.getSelectedItem().equals("gwintowana") && cboKlasaSrub.getSelectedItem().equals("4.6")){
            av = as;
            alfaV = 0.6;
        } else if (cboPlaszczyznaScinania.getSelectedItem().equals("gwintowana") && cboKlasaSrub.getSelectedItem().equals("4.8")) {
            av = as;
            alfaV = 0.5;
        } else if (cboPlaszczyznaScinania.getSelectedItem().equals("gwintowana") && cboKlasaSrub.getSelectedItem().equals("5.6")) {
            av = as;
            alfaV = 0.6;
        } else if (cboPlaszczyznaScinania.getSelectedItem().equals("gwintowana") && cboKlasaSrub.getSelectedItem().equals("5.8")) {
            av = as;
            alfaV = 0.5;
        } else if (cboPlaszczyznaScinania.getSelectedItem().equals("gwintowana") && cboKlasaSrub.getSelectedItem().equals("6.8")) {
            av = as;
            alfaV = 0.5;
        } else if (cboPlaszczyznaScinania.getSelectedItem().equals("gwintowana") && cboKlasaSrub.getSelectedItem().equals("8.8")) {
            av = as;
            alfaV = 0.6;
        } else if (cboPlaszczyznaScinania.getSelectedItem().equals("gwintowana") && cboKlasaSrub.getSelectedItem().equals("10.9")) {
            av = as;
            alfaV = 0.5;
        } else if (cboPlaszczyznaScinania.getSelectedItem().equals("niegwintowana")) {
            av = a;
            alfaV = 0.6;
        }
        
        txtAv.setText(Double.toString(av));
        txtAlfaV.setText(Double.toString(alfaV));
    }
    
    private void k2Checker() {
        if (cboLebWpuszczany.getSelectedItem().equals("TAK")) {
            k2 = 0.63;
        } else {
            k2 = 0.9;
        }
    }
    
    public void imgClear() {
        lbl1_2.setVisible(false);
        lbl1_3.setVisible(false);
        lbl1_4.setVisible(false);
        lbl1_5.setVisible(false);
        lbl1_6.setVisible(false);
        lbl2_2.setVisible(false);
        lbl2_3.setVisible(false);
        lbl2_4.setVisible(false);
        lbl2_5.setVisible(false);
        lbl2_6.setVisible(false);
    }
    
    public void rowChecker() {

        boltRow = cboBoltRow.getSelectedItem().toString();
        switch (boltRow)
        {
            case "wybierz":
                System.out.println("Wybrano wybierz row");
                imgClear();
                break;
                
            case "2":
                System.out.println("Wybrano 2 row");
                if (cboBoltColumn.getSelectedItem().equals("1")) {
                    lbl1_2.setVisible(true);
                    lbl1_3.setVisible(false);
                    lbl1_4.setVisible(false);
                    lbl1_5.setVisible(false);
                    lbl1_6.setVisible(false);
                } else if (cboBoltColumn.getSelectedItem().equals("2")) {
                    lbl2_2.setVisible(true);
                    lbl2_3.setVisible(false);
                    lbl2_4.setVisible(false);
                    lbl2_5.setVisible(false);
                    lbl2_6.setVisible(false);
                }               
                break;
                
            case "3":
                System.out.println("Wybrano 3 row");
                if (cboBoltColumn.getSelectedItem().equals("1")) {
                    lbl1_2.setVisible(false);
                    lbl1_3.setVisible(true);
                    lbl1_4.setVisible(false);
                    lbl1_5.setVisible(false);
                    lbl1_6.setVisible(false);
                } else if (cboBoltColumn.getSelectedItem().equals("2")) {
                    lbl2_2.setVisible(false);
                    lbl2_3.setVisible(true);
                    lbl2_4.setVisible(false);
                    lbl2_5.setVisible(false);
                    lbl2_6.setVisible(false);
                }
                break;
                
            case "4":
                System.out.println("Wybrano 4 row");
                if (cboBoltColumn.getSelectedItem().equals("1")) {
                    lbl1_2.setVisible(false);
                    lbl1_3.setVisible(false);
                    lbl1_4.setVisible(true);
                    lbl1_5.setVisible(false);
                    lbl1_6.setVisible(false);
                } else if (cboBoltColumn.getSelectedItem().equals("2")) {
                    lbl2_2.setVisible(false);
                    lbl2_3.setVisible(false);
                    lbl2_4.setVisible(true);
                    lbl2_5.setVisible(false);
                    lbl2_6.setVisible(false);
                }
                break;
                
            case "5":
                System.out.println("Wybrano 5 row");
                if (cboBoltColumn.getSelectedItem().equals("1")) {
                    lbl1_2.setVisible(false);
                    lbl1_3.setVisible(false);
                    lbl1_4.setVisible(false);
                    lbl1_5.setVisible(true);
                    lbl1_6.setVisible(false);
                } else if (cboBoltColumn.getSelectedItem().equals("2")) {
                    lbl2_2.setVisible(false);
                    lbl2_3.setVisible(false);
                    lbl2_4.setVisible(false);
                    lbl2_5.setVisible(true);
                    lbl2_6.setVisible(false);
                }
                break;
            case "6":
                System.out.println("Wybrano 6 row");
                if (cboBoltColumn.getSelectedItem().equals("1")) {
                    lbl1_2.setVisible(false);
                    lbl1_3.setVisible(false);
                    lbl1_4.setVisible(false);
                    lbl1_5.setVisible(false);
                    lbl1_6.setVisible(true);
                } else if (cboBoltColumn.getSelectedItem().equals("2")) {
                    lbl2_2.setVisible(false);
                    lbl2_3.setVisible(false);
                    lbl2_4.setVisible(false);
                    lbl2_5.setVisible(false);
                    lbl2_6.setVisible(true);
                }
                break;
            default:
                System.out.println("Błędne dane");
                break;
        }
    }
     
    private String makeStringReport() {
        reportString = "POŁĄCZENIE PRZEGUBOWE ZAKŁADKOWE BELKA-BELKA \n\n"
                + "Klasa stali: \t" + cboKlasaStali.getSelectedItem().toString() + "\n"
                + "Granica plastyczności stali: \t\t fy= " + fy + "\t [MPa]" + "\n"
                + "Wytrzymałość stali na rozciąganie: \t fu= " + fu + "\t [MPa]" + "\n"
                + "Częściowy współczynnik bezpieczeństwa: \t " + unicodeSymbols.gamma +"M2= " + gammaM2 + "\n"
                + "\n"
                + "Średnica śruby: \t d= " + d + "\t [mm]" + "\n"
                + "Średnica otworu: \t d0= " + d0 + "\t [mm]" + "\n"
                + "Pole przekroju trzpienia: \t A= " + a + "\t [mm2]" + "\n"
                + "Pole przekroju rdzenia: \t As= " + as + "\t [mm2]" + "\n"
                + "\n"
                + "Klasa śrub: \t" + cboKlasaSrub.getSelectedItem().toString() + "\n"
                + "Granica plastyczności stali śruby: \t fyb= " + fyb + "\t [MPa]" + "\n"
                + "Wytrzymałość stali śruby na rozciąganie: \t fub= " + fub + "\t [MPa]" + "\n"
                + "\n"
                + "Płaszczyzna ścinania przechodzi przez: \t " + cboPlaszczyznaScinania.getSelectedItem().toString() + " część śruby" + "\t alfaV= " + alfaV + "\t Av= " + av + " [mm2] \n"
                + "\n"
                + "Nośność śruby na ścinanie: \n"
                + "Fv,Rd = (alfaV * fub * Av) / Ym2 \n"
                + "Fv,Rd = (" + alfaV + " * "+ fub +" * " + av + ") / "+ gammaM2 +" = " + fVRd + " [kN] \n"
                + "\n"
                + "Nośność śruby na docisk do środnika belki: \n"
                + "- Śruba skrajna \n"
             //   + "Fb,Rd1 = (k1 * " + unicodeSymbols.alfa + "b * fu * d * tw) / Ym2 \n"   // ustawić tw jako cieńszy z łączonych elementów
                
                ;
        return reportString;
    }
    
    public void e1Checker() {
        double e1Min;
        
        e1Min = 1.2 * d0;
        
        txtE1Min.setText(Double.toString(e1Min));
        
        if (e1 >= e1Min) {
            txtE1.setForeground(Color.GREEN);   
        } else {
            txtE1.setForeground(Color.RED);
            JOptionPane.showMessageDialog(null, "Zwiększ odległość czołową otworów \"e1\" ");
        }  
    }
    
    public void p1Checker() {
        double p1Min;
        
        p1Min = 2.2 * d0;
        
        txtP1Min.setText(Double.toString(p1Min));
        
        if (p1 >= p1Min) {
            txtP1.setForeground(Color.GREEN);   
        } else {
            txtP1.setForeground(Color.RED);
            JOptionPane.showMessageDialog(null, "Zwiększ rozstaw otworów \"p1\" ");
        }  
    }
    
    public void e2Checker() {
        double e2Min;
        
        e2Min = 1.2 * d0;
        
        txtE2Min.setText(Double.toString(e2Min));
        
        if (e2 >= e2Min) {
            txtE2.setForeground(Color.GREEN);   
        } else {
            txtE2.setForeground(Color.RED);
            JOptionPane.showMessageDialog(null, "Zwiększ odległość boczną otworów \"e2\" ");
        }  
    }
    
    public void p2Checker() {
        double p2Min;
        
        p2Min = 2.4 * d0;
        
        if (cboBoltColumn.getSelectedItem().equals("2")) {
            txtP2Min.setText(Double.toString(p2Min));
            if (p2 >= p2Min) {
                txtP2.setForeground(Color.GREEN);   
            } else {
                txtP2.setForeground(Color.RED);
                JOptionPane.showMessageDialog(null, "Zwiększ rozstaw otworów \"p2\" ");
            }  
        } else {
            txtP2Min.setText("");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BeamToBeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BeamToBeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BeamToBeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BeamToBeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BeamToBeam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnRaport;
    private javax.swing.JComboBox<String> cboBoltColumn;
    private javax.swing.JComboBox<String> cboBoltRow;
    private javax.swing.JComboBox<String> cboKlasaSrub;
    private javax.swing.JComboBox<String> cboKlasaStali;
    private javax.swing.JComboBox<String> cboLebWpuszczany;
    private javax.swing.JComboBox<String> cboPlaszczyznaScinania;
    private javax.swing.JComboBox<String> cboSrednicaSrub;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel_img;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl1_2;
    private javax.swing.JLabel lbl1_3;
    private javax.swing.JLabel lbl1_4;
    private javax.swing.JLabel lbl1_5;
    private javax.swing.JLabel lbl1_6;
    private javax.swing.JLabel lbl2_2;
    private javax.swing.JLabel lbl2_3;
    private javax.swing.JLabel lbl2_4;
    private javax.swing.JLabel lbl2_5;
    private javax.swing.JLabel lbl2_6;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtAlfaV;
    private javax.swing.JTextField txtAs;
    private javax.swing.JTextField txtAv;
    private javax.swing.JTextField txtD0;
    private javax.swing.JTextField txtE1;
    private javax.swing.JTextField txtE1Min;
    private javax.swing.JTextField txtE2;
    private javax.swing.JTextField txtE2Min;
    private javax.swing.JTextField txtFtRd;
    private javax.swing.JTextField txtFu;
    private javax.swing.JTextField txtFub;
    private javax.swing.JTextField txtFvRd;
    private javax.swing.JTextField txtFy;
    private javax.swing.JTextField txtFyb;
    private javax.swing.JTextField txtGammaM2;
    private javax.swing.JTextField txtP1;
    private javax.swing.JTextField txtP1Min;
    private javax.swing.JTextField txtP2;
    private javax.swing.JTextField txtP2Min;
    private javax.swing.JTextField txtT;
    // End of variables declaration//GEN-END:variables
}
